#!/bin/bash
#
# $Id: f5,v 1.3 2023/07/03 08:30:07 jon Exp $
#
# Script to perform A + CB + C
#
# Inputs
# $1: input A
# $2: input B
# $3: input C
# $4: output
# $5: temporary stem
#
# Return codes
# 1: error in parameters
# 0: success
#
f3 $1 $3 $2 $4 $5
