#!/bin/bash
#
# $Id: two,v 1.4 2023/07/03 08:30:08 jon Exp $
#
# Script to produce _2 from _1
#
usage="$0: usage: $0 <a>"
if [ $# -ne 1 ]; then
  echo "$usage"
  exit 1
fi
echo $1 | sed -e "s/_1$/_2/g"
