#!/bin/sh
#
# Script to do zdiff in meataxe 64 until a binary is available
#
# Parameters as for zdiff in meataxe 2000
# ie [-m <memory] <infile> <outfile> <count>
#
if [ $# -ne 2 ]; then
   echo "zdiff: bad parameters"
   echo "usage: zdiff [-m <memory] <file1> <file2>"
   exit 1
fi
file1=$1
file2=$2
tmp=tmp$$
to_m2000 ${file1} ${tmp}.1
to_m2000 ${file2} ${tmp}.2
~/install/zdiff ${tmp}.1 ${tmp}.2
ret=$?
rm ${tmp}.{1,2}
exit $ret
