#!/bin/sh
#
# Script to do ziv in meataxe 64 until a binary is available
#
# Parameters as for ziv in meataxe 2000
# ie [-m <memory] <infile> <outfile>
#
mem=
if [ "-m" = "$1" ]; then
    mem="-m $2"
    shift 2
fi
if [ $# -ne 2 ]; then
   echo "ziv: bad parameters"
   echo "usage: ziv [-m <memory] <infile> <outfile>"
   exit 1
fi
infile=$1
outfile=$2
tmp=tmp$$
to_m2000 ${infile} ${tmp}.1
~/install/ziv ${mem} ${tmp}.1 ${tmp}.2
ret=$?
# Now convert back the result
if [ 0 -eq ${ret} ]; then
    to_m64 ${tmp}.2 ${outfile}
fi
rm -f ${tmp}.{1,2} ${gens}
exit ${ret}
