#!/bin/sh
#
# Script to do zivf in meataxe 64 until a binary is available
#
# Parameters as for zivf in meataxe 2000
# ie [-m <memory] <infile> <outfile> <temp dir>
#
mem=
if [ "-m" = "$1" ]; then
    mem="-m $2"
    shift 2
fi
if [ $# -ne 3 ]; then
   echo "zivf: bad parameters"
   echo "usage: zivf [-m <memory] <infile> <outfile> <temp dir>"
   exit 1
fi
infile=$1
outfile=$2
tmp_dir=$3
tmp=tmp$$
to_m2000 ${infile} ${tmp}.1
~/install/zivf ${mem} ${tmp}.1 ${tmp}.2 ${tmp_dir}
ret=$?
# Now convert back the result
if [ 0 -eq ${ret} ]; then
    to_m64 ${tmp}.2 ${outfile}
fi
rm -f ${tmp}.{1,2} ${gens}
exit ${ret}
