#!/bin/sh
#
# Script to do zmsp in meataxe 64 until a binary is available
#
# Parameters as for zmsp in meataxe 2000
# ie [-m <memory] <infile> <outfile> <generators>
#
dir=`dirname $0`
if [ "-m" = "$1" ]; then
    shift 2
fi
if [ $# -le 3 ]; then
   echo "zmsp: bad parameters"
   echo "usage: zmsp [-m <memory] <infile> <outfile> <generators>"
   exit 1
fi
infile=$1
outfile=$2
shift 2
tmp=tmp$PPID
out=`${dir}/../bin/zsp.sh ${infile} ${tmp}.ss 2 0 $*`
ret=$?
if [ 1 -eq $ret ]; then
    if [ -e ${tmp}.ss.bs -a ${tmp}.ss.rem ]; then
        ret=0
    fi
fi
if [ 0 -eq $ret ]; then
    # Success
    ${dir}/../bin/zex ${tmp}.ss.{bs,rem} ${tmp}.out
    ${dir}/../bin/zng ${tmp}.out ${outfile}
    rm ${tmp}.ss.{bs,rem} ${tmp}.out
    ${dir}/../bin/znor ${outfile}
    exit 0
else
    # Failure
    rm -f ${tmp}.ss*
    exit 1
fi
