#!/bin/sh
#
# Script to do zmu in meataxe 64 until a binary is available
#
# Parameters as for zmu in meataxe 2000
# ie [-m <memory] <infile1> <infile2> <outfile>
#
dir=`dirname $0`
if [ "$1" = "-m" ]; then
    shift 2 # Ignore -m <memory
fi
if [ $# -ne 3 ]; then
   echo "zmu: bad parameters"
   echo "usage: zmu [-m <memory] <infile1> <infile2> <outfile>"
   exit 1
fi
infile1=$1
infile2=$2
outfile=$3
${dir}/../bin/zmu ${infile1} ${infile2} ${outfile}
ret=$?
