#!/bin/sh
#
# Script to do zns in meataxe 64 until a binary is available
#
# Parameters as for zns in meataxe 2000
# ie [-m <memory] <infile> <outfile>
#
if [ $# -ne 2 -a $# -ne 4 ]; then
   echo "zns: bad parameters"
   echo "usage: zns [-m <memory] <infile> <outfile>"
   exit 1
fi
mem=
if [ 4 -eq $# ]; then
    mem="-m $2"
    shift 2
fi
infile=$1
outfile=$2
tmp=tmp$$
to_m2000 ${infile} ${tmp}.1
out=`~/install/zns ${mem} ${tmp}.1 ${tmp}.2`
ret=$?
if [ 0 == ${ret} -a "0" != "${out}" ]; then
    to_m64 ${tmp}.2 ${outfile}
    rm ${tmp}.2
fi
echo ${out}
rm ${tmp}.1
exit ${ret}
