#!/bin/sh
#
# Script to do zqs in meataxe 64 until a binary is available
#
# Parameters as for zqs in meataxe 2000
# ie [-m <memory] <range> <generator> <output>
#
if [ $# -ne 3 -a $# -ne 5 ]; then
   echo "zqs: bad parameters"
   echo "usage: zqs [-m <memory] <range> <generator> <output>"
   exit 1
fi
mem=
if [ 5 -eq $# ]; then
    mem="-m $2"
    shift 2
fi
range=$1
generator=$2
outfile=$3
tmp=tmp$$
to_m2000 ${range} ${tmp}.1
to_m2000 ${generator} ${tmp}.2
~/install/zqs ${mem} ${tmp}.1 ${tmp}.2 ${tmp}.3
to_m64 ${tmp}.3 ${outfile}
rm ${tmp}.{1,2,3}
