#!/bin/sh
#
# Script to do zscript in meataxe 64
#
# Parameters as for zscript in meataxe 2000
# ie [-m <memory] <outfile> <tmp> <script> <generators>
#
dir=`dirname $0`
if [ "-m" = "$1" ]; then
    shift 2
fi
if [ "-mg" = "$1" ]; then
    shift 2
fi
${dir}/../bin/zscript $*
ret=$?
exit ${ret}
