#!/bin/sh
#
# Script to do zsel in meataxe 64 until a binary is available
#
# Parameters as for zsel in meataxe 2000
# ie [-m <memory] <infile1> <outfile> <index>
#
dir=`dirname $0`
if [ "$1" = "-m" ]; then
    shift 2 # Ignore -m <memory
fi
if [ $# -ne 3 ]; then
   echo "zsel: bad parameters"
   echo "usage: zsel [-m <memory] <infile> <index> <outfile>"
   exit 1
fi
infile=$1
outfile=$2
index=$3
${dir}/../bin/zsv ${infile} ${index} ${outfile}
ret=$?
exit ${ret}
