#!/bin/bash
#
# Script to do zsel in meataxe 64 until a binary is available
#
# Parameters as for zsel in meataxe 2000
# ie [-m <memory] <infile1> <outfile> <index>
#
dir=`dirname $0`
if [ "$1" = "-m" ]; then
    shift 2 # Ignore -m <memory
fi
if [ $# -ne 3 ]; then
   echo "zsel: bad parameters"
   echo "usage: zsel [-m <memory] <infile> <outfile> <index>"
   exit 1
fi
infile=$1
outfile=$2
index=$3
tmp=tmp$$
nor=`znor ${infile}`
if [ 0 -ne $? ]; then
    echo "$0: ${infile}: cannot get number of rows, terminating"
    exit 1
fi
if [ ${index} -ge $nor ]; then
    echo "$0: ${index} is out of range for ${infile}, terminating"
    exit 1
fi
echo $nor > ${tmp}.1
echo 1 >> ${tmp}.1
i=0
while [ $i -lt ${index} ]; do
    echo 0 >> ${tmp}.1
    let i=$i+1
done
echo 1 >> ${tmp}.1
let i=$i+1
while [ $i -lt ${nor} ]; do
    echo 0 >> ${tmp}.1
    let i=$i+1
done
${dir}/../bin/zut 1 ${tmp}.2 $nor 1 < ${tmp}.1
if [ 0 -ne $? ]; then
    echo "$0: ${infile}: cannot produce bitstring, terminating"
    exit 1
fi
${dir}/../bin/zrx ${tmp}.2 ${infile} ${outfile} ${tmp}.3
if [ 0 -ne $? ]; then
    echo "$0: ${infile}: cannot extract row ${index}, terminating"
    exit 1
fi
rm ${tmp}.{1,2,3}
exit 0
