#!/bin/sh
#
# Script to do zsid in meataxe 64 until a binary is available
#
# Parameters as for zsid in meataxe 2000
# ie [-m <memory] <field order> <nor> <noc> <elt> <out_file>
#
if [ $# -ne 5 -a $# -ne 7 ]; then
   echo "zsid: bad parameters"
   echo "usage: zsid [-m <memory] <field order> <nor> <noc> <elt> <out_file>"
   exit 1
fi
mem=
if [ 7 -eq $# ]; then
    mem="-m $2"
    shift 2
fi
prime=$1
nor=$2
noc=$3
elt=$4
outfile=$5
tmp=tmp$$
~/install/zsid ${mem} ${prime} ${nor} ${noc} ${elt} ${tmp}.1
ret=$?
to_m64 ${tmp}.1 ${outfile}
rm ${tmp}.1
exit $ret
