#!/bin/sh
#
# Script to do zsign in meataxe 64 until a binary is available
#
# Parameters as for zsign in meataxe 2000
# ie [-m <memory] <infile> <outfile>
#
if [ $# -ne 2 -a $# -ne 4 ]; then
   echo "zsign: bad parameters"
   echo "usage: zsign [-m <memory] <quadratic form> <bilinear form>"
   exit 1
fi
mem=
if [ 4 -eq $# ]; then
    mem="-m $2"
    shift 2
fi
qf=$1
bf=$2
tmp=tmp$$
to_m2000 ${qf} ${tmp}.1
to_m2000 ${bf} ${tmp}.2
~/install/zsign ${mem} ${tmp}.1 ${tmp}.2
rm ${tmp}.{1,2}
