#!/bin/sh
#
# Script to do zspan in meataxe 64 until a binary is available
#
# Parameters as for zspan in meataxe 2000
# ie [-m <memory] <infile> <outfile> <count>
#
if [ $# -ne 3 ]; then
   echo "zspan: bad parameters"
   echo "usage: zspan [-m <memory] <infile> <outfile> <count>"
   exit 1
fi
infile=$1
outfile=$2
count=$3
tmp=tmp$$
to_m2000 ${infile} ${tmp}.1
~/install/zspan ${tmp}.1 ${tmp}.2 ${count}
to_m64 ${tmp}.2 ${outfile}
rm ${tmp}.{1,2}
