#!/bin/sh
#
# $Id: base_from_vector,v 1.2 2002/07/05 17:19:22 jon Exp $
#
# Script to find a representation in standard base, given a vector
#
# Inputs
# $1: vector with which to split
# $2: output filename base
# $3: the standard basis
# $4: generator a
# $5-: other generators
#
# outputs will be of the form <$2>_sb_{1,...}
# where nor is number of rows, and q is the prime power
#
#
# Return codes
# 1: error in parameters
# 0: success
# 254: reducible
#
#set -v
. functions
usage="$0: usage: $0 <e> <output_stem> <s> <a>  [<other generators>*]"
if [ $# -lt 5 ]; then
  echo $usage
  exit 1;
fi
e=$1
o=$2
s=$3
a=$4
if [ -e $e -a -e $a ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $noc -ne `znoc $e` ]; then
    echo "$0: $a and $e are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $e or $a"
  exit 1
fi
tmp=tmp${PPID}
memory=200
shift 4
base_with_vector $e $s $memory $a $*
ret=$?
if [ 0 -ne $ret ]; then
  rm -f ${tmp}*
  exit $ret
fi
conjugate $s ${o} $a $*
ret=$?
rm -f ${tmp}*
exit $ret
