#!/bin/bash
#
# $Id: base_from_vector,v 1.7 2023/07/03 08:30:06 jon Exp $
#
# Script to find a representation in standard base, given a vector
#
# Inputs
# $1: vector with which to split
# $2: output filename base
# $3: memory
# $4: the standard basis
# $5: generator a
# $6-: other generators
#
# outputs will be of the form <$2>_sb_{1,...}
# where nor is number of rows, and q is the prime power
#
#
# Return codes
# 1: error in parameters
# 0: success
# 254: reducible
#
#set -v
. functions
usage="$0: usage: $0 <e> <output_stem> <memory> <s> <a>  [<other generators>*]"
if [ $# -lt 6 ]; then
  echo "$usage"
  exit 1;
fi
e=$1
o=$2
memory=$3
s=$4
a=$5
if [ -e $e -a -e $a ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $noc -ne `znoc $e` ]; then
    echo "$0: $a and $e are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $e or $a"
  exit 1
fi
tmp=tmp${PPID}
shift 5
base_with_vector $e $s $memory $a $*
ret=$?
if [ 0 -ne $ret ]; then
  rm -f ${tmp}*
  exit $ret
fi
conjugate $s ${o} $a $*
ret=$?
rm_all ${tmp}
exit $ret
