#!/bin/sh
#
# $Id: bn,v 1.2 2005/06/21 19:43:40 jon Exp $
#
# Compute bn(x)
#
# Inputs
# $1: input
# $2: power
# $3: output
#
# Return codes
# 1: error in parameters
# 0: success
#
#set -x
usage="$0: usage: $0 <mat> <n> <out>"
if [ 3 -ne $# ]; then
  echo $usage
  exit 1;
fi

tmp=tmp${PPID}
a=$1
n=$2
o=$3
let x=$n/2
let y=$n-2*$x
if [ 1 -ne $y ]; then
  echo $n not congruent to 1 mod 2
  exit 1
fi
i=1
while [ $i -le $x ]; do
  let y=$i*$i
  let z=$y/$n
  let j=$y-$z*$n # Square and reduce modulo n
  powers[$i]=$j
  let i=$i+1
done
. xn
