#!/bin/bash
#
# $Id: cn,v 1.3 2023/07/03 08:30:07 jon Exp $
#
# Compute cn(x)
#
# Inputs
# $1: input
# $2: power
# $3: output
#
# Return codes
# 1: error in parameters
# 0: success
#
#set -x
usage="$0: usage: $0 <mat> <n> <out>"
if [ 3 -ne $# ]; then
  echo $usage
  exit 1;
fi

a=$1
n=$2
o=$3
repeat=3
. yn
