#!/bin/sh
#
# $Id: cn,v 1.1 2005/06/23 21:48:47 jon Exp $
#
# Compute cn(x)
#
# Inputs
# $1: input
# $2: power
# $3: output
#
# Return codes
# 1: error in parameters
# 0: success
#
#set -x
usage="$0: usage: $0 <mat> <n> <out>"
if [ 3 -ne $# ]; then
  echo $usage
  exit 1;
fi

tmp=tmp${PPID}
a=$1
n=$2
o=$3
let x=$n/3
let x3=$x*3
let y=$n-$x3
if [ 1 -ne $y ]; then
  echo $n not congruent to 1 mod 3
  exit 1
fi
i=1
while [ $i -le $x3 ]; do
  let y=$i*$i*$i
  let z=$y/$n
  let j=$y-$z*$n # Cube and reduce modulo n
  powers[$i]=$j
  let i=$i+1
done
repeat=3
. xn
