#!/bin/sh
#
# $Id: commutate,v 1.2 2005/05/12 18:14:59 jon Exp $
#
# Script to produce a commutator
#
# Inputs
# $1: input 1
# $2: input 2
# $3: output
# $4: memory (optional)
#
# Return codes
# 1: error in parameters
# 0: success
#
usage="$0: usage: $0 <in1> <in2> <out>"
tmp=tmp${PPID}
. functions
if [ $# -ne 5 -a $# -ne 4 ]; then
  echo "$usage"
  exit 1;
fi
a=$1
b=$2
o=$3
if [ 5 -eq $# ]; then
  memory=$4
else
  memory=400
fi
if [ -e $1 -a -e $2 ]; then
  zmu -m $memory $b $a ${tmp}_ba
  ret=$?
  if [ 0 -ne $ret ]; then
    rm ${tmp}*
    exit $ret
  fi
  zivf -m $memory ${tmp}_ba ${tmp}_ba_iv .
  ret=$?
  if [ 0 -ne $ret ]; then
    rm ${tmp}*
    exit $ret
  fi
  zmu -m $memory ${tmp}_ba_iv $a  ${tmp}_ba_iv_a
  ret=$?
  if [ 0 -ne $ret ]; then
    rm ${tmp}*
    exit $ret
  fi
  zmu -m $memory ${tmp}_ba_iv_a $b $o
  ret=$?
  if [ 0 -ne $ret ]; then
    rm ${tmp}*
    exit $ret
  fi
  rm ${tmp}*
else
  echo "$0: missing files $1 or $2"
  exit 1
fi
