#!/bin/sh
#
# $Id: cut_cols,v 1.2 2002/06/25 10:30:12 jon Exp $
#
# Script to cut some vectors to leading subvector
#
# Inputs
# $1: vectors
# $2: number of columns to leave
# $3: output file
#
# Return codes
# 1: error in parameters
# 0: ok
#
#set -v
usage="$0: usage: $0 <i> <n> <o>"
if [ $# -ne 3 ]; then
  echo $usage
  exit 1;
fi
i=$1
n=$2
o=$3
if [ -e $i ]; then
  q=`zprime $i`
  nor=`znor $i`
  noc=`znoc $i`
else
  echo "$0: missing file $i"
  exit 1
fi
if [ $n -gt $noc ]; then
  echo "$0: $n > znor $i"
  exit 1
fi
tmp=tmp${PPID}
zid $q $noc $n ${tmp}.0
ret=$?
if [ $ret -ne 0 ]; then
  echo failed to create id
  exit $ret
fi
zmu $i ${tmp}.0 $o
ret=$?
rm -f ${tmp}.0
exit $ret
