#!/bin/sh
#
# $Id: dual_with_order,v 1.8 2014/07/15 17:46:37 jon Exp $
#
# Script to dual of a matrix, given its order
#
# Inputs
# $1: matrix
# $2: out
# $3: order
# $4: memory (optional)
#
# Return codes
# 1: error in parameters
# 0: success
#
#set -v
. functions
usage="$0: usage: $0 <in> <out> <order> [<memory>]"
if [ $# -ne 3 -a $# -ne 4 ]; then
  echo "$usage"
  exit 1;
fi
a=$1
o=$2
tmp=tmp${PPID}
tr=${tmp}.0
o_a=$3
if [ -e $a ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
else
  echo "$0: missing file $a"
  exit 1
fi
if [ $# -eq 3 ]; then
  memory=400
else
  memory=$4
fi
ztr -m $memory $a ${tr}
ret=$?
if [ 0 -ne $ret ]; then
  rm -f ${tmp}*
  exit $ret
fi
if [ $o_a -gt 2 ]; then
  let index=${o_a}-1
  power ${tr} $index $o $memory
  if [ 0 -ne $ret ]; then
    rm -f ${tmp}*
    exit $ret
  fi
else
  cp ${tr} $o
  ret=$?
fi
rm -f ${tmp}*
exit $ret
