#!/bin/sh
#
# $Id: f3,v 1.5 2002/09/11 21:20:47 jon Exp $
#
# Script to perform A + BC + B
#
# Inputs
# $1: input A
# $2: input B
# $3: input C
# $4: output
# $5: temporary stem
#
# Return codes
# 1: error in parameters
# 0: success
#
usage="$0: usage: $0 <in1> <in2> <in3> <out> <stem>"
if [ $# -ne 5 ]; then
  echo "$usage"
  exit 1;
fi
if [ -e $1 -a -e $2 -a -e $3 ]; then
  zmu $2 $3 ${5}_1 400
  if [ $? -ne 0 ]; then
    exit 1
  fi
  f1 $1 ${5}_1 $2 $4 ${5}_1
  rm ${5}_1
else
  echo "$0: missing files $1, $2 or $3"
  exit 1
fi
