#!/bin/sh
#
# $Id: f3,v 1.7 2003/07/28 21:06:33 jon Exp $
#
# Script to perform A + BC + B
#
# Inputs
# $1: input A
# $2: input B
# $3: input C
# $4: output
# $5: temporary stem
#
# Return codes
# 1: error in parameters
# 0: success
#
. functions
usage="$0: usage: $0 <in1> <in2> <in3> <out> <stem>"
if [ $# -ne 5 ]; then
  echo "$usage"
  exit 1;
fi
if [ -e $1 -a -e $2 -a -e $3 ]; then
  memory=400
  ok=0
  while [ 0 -eq $ok ]; do
    zmu -m $memory $2 $3 ${5}_1
    ret=$?
    if [ $ret -eq 0 ]; then
      ok=1
    elif [ $ret -eq 2 ]; then
      let memory=`more_memory $memory 2>/dev/null`
    else
      exit 1
    fi
  done
  f1 $1 ${5}_1 $2 $4 ${5}_1
  rm ${5}_1
else
  echo "$0: missing files $1, $2 or $3"
  exit 1
fi
