#!/bin/sh
#
# $Id: f4,v 1.2 2002/06/25 10:30:12 jon Exp $
#
# Script to perform A + CB + B
#
# Inputs
# $1: input A
# $2: input B
# $3: input C
# $4: output
# $5: temporary stem
#
# Return codes
# 1: error in parameters
# 0: success
#
f2 $1 $3 $2 $4 $5
