#!/bin/sh
#
# $Id: f9,v 1.6 2002/10/13 14:16:08 jon Exp $
#
# Script to perform A + B + CC
#
# Inputs
# $1: input A
# $2: input B
# $3: input C
# $4: output
# $5: temporary stem
#
# Return codes
# 1: error in parameters
# 0: success
#
usage="$0: usage: $0 <in1> <in2> <in3> <out> <stem>"
if [ $# -ne 5 ]; then
  echo "$usage"
  exit 1;
fi
if [ -e $1 -a -e $2 -a -e $3 ]; then
  zmu -m 400 $3 $3 ${5}_1
  if [ $? -ne 0 ]; then
    exit 1
  fi
  f1 $1 $2 ${5}_1 $4 ${5}_1
  rm ${5}_1
else
  echo "$0: missing files $1, $2 or $3"
  exit 1
fi
