#!/bin/sh
#
# $Id: find_nullity_one,v 1.7 2002/06/25 10:30:12 jon Exp $
#
# Script to find an element of nullity one in two generators
#
# Inputs
# $1: generator a
# $2: generator b
# $3: output file name
# $4: initial memory (optional)
#
# Return codes
# 1: error in parameters
# 0: success
# 254: nullity not 1
#
usage="$0: usage: $0 <a> <b> <out> [<memory>]"
if [ $# -ne 3 -a $# -ne 4 ]; then
  echo $usage
  exit 1;
fi
. functions
a=$1
b=$2
e=$3
ok=0
if [ $# -eq 3 ]; then
  memory=200
else
  memory=$4
fi
nor=`znor $a`
q=`zprime $a`
# First compute o_a and o_b
o_a=`singular_order $a`
ret=$?
if [ 0 -ne $ret ]; then
  echo Cannot compute order of $a
  exit 1
fi
o_b=`singular_order $b`
ret=$?
if [ 0 -ne $ret ]; then
  echo Cannot compute order of $b
  exit 1
fi
exec find_nullity_one_with_orders $a $b $e $o_a $o_b $memory
