#!/bin/sh
#
# $Id: find_best_nullity_with_orders,v 1.5 2002/09/11 21:20:47 jon Exp $
#
# Script to find an element of best nullity in two generators
#
# Inputs
# $1: output file name
# $2: initial memory
# $3: generator a
# $4: order a
# $5: generator b
# $6: order b
# $7-: further generators and orders
#
# Return codes
# 1: error in parameters
# 0: success
# 254: couldn't find a suitable element
#
usage="$0: usage: $0 <out> <memory> <a> <order a> <b> <order b> [<further generators and orders>]"
if [ $# -lt 6 ]; then
  echo "$usage"
  exit 1;
fi
. functions
e=$1
memory=$2
a=$3
o_a=$4
b=$5
o_b=$6
shift 2
tmp=tmp${PPID}
ok=0
nor=`znor $a`
while [ $ok -eq 0 ]; do
  out=`zfln ${tmp}.zsums 10 $nor $memory $* 2>/dev/null`
  ret=$?
  if [ 2 -eq $ret ]; then
    let memory=`more_memory $memory`
  elif [ 0 -eq $ret ]; then
    ok=1
    name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
    cp ${name} $e
    echo $out | sed -e "s/^.*form //g;s/ .*$//g"
  else
    echo Failed to find a suitable element
    rm -f ${tmp}*
    exit 254
  fi
done
