#!/bin/sh
#
# $Id: find_best_nullity_with_orders,v 1.2 2002/09/05 18:22:51 jon Exp $
#
# Script to find an element of best nullity in two generators
#
# Inputs
# $1: generator a
# $2: generator b
# $3: output file name
# $4: order a
# $5: order b
# $6: initial memory (optional)
#
# Return codes
# 1: error in parameters
# 0: success
# 254: couldn't find a suitable element
#
usage="$0: usage: $0 <a> <b> <out> <order a> <order b> [<memory>]"
if [ $# -ne 5 -a $# -ne 6 ]; then
  echo $usage
  exit 1;
fi
. functions
a=$1
b=$2
e=$3
o_a=$4
o_b=$5
tmp=tmp${PPID}
ok=0
if [ $# -eq 5 ]; then
  memory=200
else
  memory=$6
fi
nor=`znor $a`
q=`zprime $a`
# Try zsums
while [ $ok -eq 0 ]; do
  out=`zfln $a $b ${tmp}.zsums $o_a $o_b 10 $nor $memory 2>/dev/null`
  ret=$?
  if [ 2 -eq $ret ]; then
    let memory=`more_memory $memory`
  elif [ 0 -eq $ret ]; then
    ok=1
    name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
    cp ${name} $e
    echo $out | sed -e "s/^.*form //g;s/ .*$//g"
  else
    echo Failed to find a suitable element
    rm -f ${tmp}*
    exit 254
  fi
done
