#!/bin/sh
#
# $Id: functions,v 1.5 2002/06/25 10:30:12 jon Exp $
#
# Functions to support the meataxe scripts
#
function more_memory()
{
  local x
  if [ $1 -ge 102400 ]; then
    let x=$1+51200
  else
    let x=$1*2
  fi
  echo $x
}

function new_name_from_name()
{
  local name
  name=$1
  if [ -e ${name}_1 ]; then
    x=1
    while [ -e ${name}_${x}_1 ]; do
      let x=$x+1
    done
    name=${name}_${x}
  fi
  echo $name
}

function new_name()
{
  local o
  local nor
  local dim
  local x
  o=$1
  nor=$2
  dim=$3
  name=${o}_${nor}_${dim}
  echo `new_name_from_name $name`
}

function new_irred_name()
{
  local base
  local x
  base=$1
  x=0
  while [ -e ${base}_${x}_1 ]; do
    let x=$x+1
  done
  echo ${base}_${x}
}

function fsize()
{
  local x
  x=`ls -s -k $1 | sed -e "s/^ *//g;s/  *.*$//g"`
  echo $x
}
