#!/bin/sh
#
# $Id: hyperbolic,v 1.1 2002/10/04 17:15:06 jon Exp $
#
# Script to determine if a 2 dimensional space is hyperbolic wrt a quadratic form
#
# Inputs
# $1: initial memory
# $2: space S
# $3: form Q
#
# Return codes
# 1: error in parameters
# 0: space is hyperbolic
# 255: space is definite
# 254: space had dimension not 2
#
# Output on stdout, the rank, 0 or 1
#
#set -v
. functions
usage="$0: usage: $0 <memory> <S> <Q>"
if [ $# -ne 3 ]; then
  echo "$usage"
  exit 1;
fi
definite $*
ret=$?
if [ 0 -eq $ret ]; then
  exit 255
elif [ 255 -eq $ret ]; then
  exit 0
else
  exit $ret
fi
