#!/bin/sh
#
# $Id: indicatef_with_script,v 1.8 2006/12/27 19:09:52 jon Exp $
#
# Script to find the indicator of an irreducible representation,
# given a script describing the null generator
# Assumes a and b in standard base form
#
# Inputs
# $1: script for finding standard base generator
# $2: initial memory
# $3: temporary directory
# $4: a name for the form
# $5: generator a
# $6: order a
# $7: generator b
# $8: order b
# $9-: other generators and orders
#
# Return codes
# 1: error in parameters
# 0: ok
#
usage="$0: usage: $0 <script> <memory> <tmp directory> <form> <a> <order a> <b> <order b> [<other generators and orders>]"
if [ $# -lt 8 ]; then
  echo "$usage"
  exit 1;
fi
. functions
script=$1
memory=$2
tmp_dir=$3
form=$4
a=$5
b=$7
o_a=$6
o_b=$8
shift 4
if [ -e $a -a -e $b ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo "$0: $a and $b are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
tmp=tmp${PPID}
i=1
line=
duals=
while [ $# -gt 0 ]; do
  if [ 1 -eq $# ]; then
    rm -f ${tmp}.*
    echo "$usage"
    exit 1
  fi
  duals="$duals ${tmp}.$i"
  dual_with_order $1 ${tmp}.$i $2 $memory
  line="$line $1 ${tmp}.$i"
  let i=$i+1
  shift 2
done
e=${tmp}.e
ok=0
while [ $ok -eq 0 ]; do
  zscript -m $memory $e ${tmp}zscript $script $duals
  ret=$?
  if [ $ret -eq 2 ]; then
    let memory=`more_memory $memory`
  elif [ $ret -ne 0 ]; then
    echo zscript failed
    rm -f ${tmp}.*
    exit $ret
  else
    ok=1
  fi
done
rm ${tmp}zscript*
indicatef_with_element $e $script $memory $tmp_dir $form $line
ret=$?
rm -f ${tmp}.*
exit $ret
