#!/bin/sh
#
# $Id: indicate_with_orders,v 1.6 2002/06/30 21:33:15 jon Exp $
#
# Script to find the indicator of an irreducible representation
# Assumes a and b in standard base form
#
# Inputs
# $1: generator a
# $2: generator b
# $3: order a
# $4: order b
# $5: initial memory (optional)
#
# Return codes
# 1: error in parameters
# 0: ok
#
usage="$0: usage: $0 <a> <b> <order a> <order b> [<memory>]"
if [ $# -ne 4 -a $# -ne 5 ]; then
  echo $usage
  exit 1;
fi
. functions
a=$1
b=$2
o_a=$3
o_b=$4
if [ -e $a -a -e $b ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo "$0: $a and $b are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
if [ $# -eq 5 ]; then
  memory=$5
else
  memory=200
fi
tmp=tmp${PPID}
a_d=${tmp}.0
b_d=${tmp}.1
dual_with_order $a $a_d $o_a $memory
dual_with_order $b $b_d $o_b $memory
e=${tmp}.2
script=`find_nullity_one_with_orders $a_d $b_d $e $o_a $o_b $memory`
ret=$?
if [ $ret -ne 0 ]; then
  rm -f ${tmp}.*
  echo $script
  exit $ret
fi
indicate_with_element $a $b $e $a_d $b_d $script $memory
ret=$?
rm -f ${tmp}.*
exit $ret

