#!/bin/sh
#
# $Id: indicate,v 1.6 2002/09/12 11:47:28 jon Exp $
#
# Script to find the indicator of an irreducible representation
# Assumes a and b in standard base form
#
# Inputs
# $1: initial memory
# $2: generator a
# $3-: others generators
#
# Return codes
# 1: error in parameters
# 0: ok
#
usage="$0: usage: $0 <memory> <a> <b> [<other generators>]"
if [ $# -lt 3 ]; then
  echo "$usage"
  exit 1;
fi
. functions
memory=$1
a=$2
b=$3
shift
if [ -e $a -a -e $b ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo "$0: $a and $b are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
# First compute orders
line=
for x in $*; do
  o=`order $x`
  ret=$?
  if [ 0 -ne $ret ]; then
    echo Cannot compute order of $x
    exit 1
  fi
  line="$line $x $o"
done
exec indicate_with_orders $memory $line
