#!/bin/sh
#
# $Id: lift_vectors,v 1.1 2003/12/28 12:46:12 jon Exp $
#
# Script to lift a subspace through several intervening subspaces, adding
# the intervening subspaces
#
# Inputs
# $1: output subspace
# $2: input subspace
# $3: memory
# $4-: further subspaces, in the correct order
#
# Return codes
# 2: out of memory
# 1: error in parameters
# 0: ok
#
#set -v
. functions
usage="$0: usage: $0 <output> <input> <memory> <subspace> [<other subspaces>]"
if [ $# -lt 4 ]; then
  echo "$usage"
  exit 1;
fi
out=$1
in=$2
memory=$3
shift 3
if [ -e $in ]; then
  q=`zprime $in`
  if [ 1 -eq $q ]; then
    echo "$0: $in cannot be a map"
    exit 1
  fi
else
  echo "$0: missing file $in"
  exit 1
fi
tmp=tmp${PPID}
first=$in
tmp1=${tmp}.1
tmp2=${tmp}.2
for x in $* ; do
  zlv -m $memory $x $first ${tmp1}
  ret=$?
  if [ 0 -ne $ret ]; then
    rm -f ${tmp}*
    exit $ret
  fi
  zjoin -m $memory ${tmp1} $x ${tmp2}
  ret=$?
  if [ 0 -ne $ret ]; then
    rm -f ${tmp}*
    exit $ret
  fi
  first=${tmp2}
done
mv $first $out
rm -f ${tmp}*
exit 0
