#!/bin/sh
#
# $Id: new_irred_and_indicate_with_orders,v 1.9 2006/12/27 19:09:52 jon Exp $
#
# Script to classify an irreducible representation
#
# Inputs
# $1: initial memory
# $1: a name for the form
# $3: generator a
# $4: order a
# $5: generator b
# $6: order b
# $7-: other generators and orders
#
# outputs will be of the form irred/${nor}_${i}_{1,..}
# where nor = znor $a and i is an available unused index
#
#
# Return codes
# 1: error in parameters
# 0: new irreducible
# 254: no nullity one element found
# 255: existing irreducible
#
usage="$0: usage: $0 <memory> <form> <a> <order a> <b> <order b> [<other generators and orders>]"
if [ $# -lt 6 ]; then
  echo "$usage"
  exit 1;
fi
. functions
memory=$1
form=$2
a=$3
o_a=$4
b=$5
o_b=$6
if [ -e $a -a -e $b ]; then
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo $a and $b are not compatible
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
shift 2
out=`new_irred_with_orders $memory $*`
ret=$?
echo $out
script=`echo $out | sed -e "s/^.*using script //g"`
new_name=`echo $out | sed -e "s/^Found a new irreducible //g;s/ of dimension .*$//g"`
if [ 0 -eq $ret ]; then
  i=1
  line=
  while [ $# -gt 0 ]; do
    if [ 1 -eq $# ]; then
      rm -f ${tmp}.*
      echo "$usage"
      exit 1
    fi
    line="$line ${new_name}_$i $2"
    let i=$i+1
    shift 2
  done
  indicate_with_script $script $memory $form $line
fi
exit 0
