#!/bin/sh
#
# $Id: new_irred,v 1.12 2004/11/24 21:42:43 jon Exp $
#
# Script to classify an irreducible representation by
# first trying against existing irreducibles of the same degree
# Will only try if there is a unique such irreducible
#
# Inputs
# $1: initial memory
# $2-: generators
#
# Return codes
# 1: error in parameters
# 0: new irreducible
# 254: no nullity one element found
# 255: existing irreducible
#
name=$0
usage="$name: usage: $name <memory> <a> [<other generators>]"
if [ $# -lt 3 ]; then
  echo "$usage"
  exit 1;
fi
. functions
memory=$1
shift
a=$1
b=$2
if [ -e $a -a -e $b ]; then
  q=`zprime $a`
  r=`zprime $b`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo "$0: $a and $b are not compatible"
    exit 1
  fi
  if [ 1 -eq $q -a 1 -eq $r ]; then
    echo "$0: representation on two maps cannot be irreducible"
    exit 1
  fi
  if [ 1 -ne $q -a 1 -ne $r -a $q -ne $r ]; then
    echo "$0: $a and $b are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
#
# Try unique existing irred if it exists first
#
if [ -d irreds ]; then
  # irreds exists
  w=irreds/${nor}_0
  if [ -f irreds/${nor}_0_1 ]; then
    # at least one irreducible
    irreds=`ls irreds/${nor}_*_1 | wc -l`
    if [ 1 -eq $irreds ]; then
      # precisely one, get its script
      y=`ls ${w}_1_I*`
      ret=$?
      if [ 0 -ne $ret ]; then
        echo "$name: failed to find irreducible script for ${w}"
      else
        script=`echo $y | sed -e "s?${w}_1_??g"`
        ret=$?
        if [ 0 -ne $ret ]; then
          echo "$name: failed to produce irreducible script for ${w}, terminating"
        else
          # got the script, use it to form a standard basis
          out=`new_irred_with_script $memory $script $*`
          ret=$?
          if [ 0 -ne $ret ]; then
            echo $out
            exit $ret
            # Exit on existing irred or error
          else
            # New irreducible found, we need to do things properly
            new=`echo $out | sed -e "s/^Found a new irreducible //g;s/ of dimension.*$//g"`
            rm ${new}_*
            # And try properly
          fi
        fi
      fi
    fi
  fi
fi
i=0
for x in $*; do
  ord=`singular_order $x`
  ret=$?
  if [ 1 -eq $ret ]; then
    echo Cannot compute order of $x
    exit 1
  fi
  if [ 0 -eq $ret ]; then
    order[$i]=$ord
    y[$i]=$x
    let i=$i+1
  elif [ 255 -eq $ret ]; then
    zero=$x
    continue
  else
    echo singular_order returns unexpected code $ret
    exit 1
  fi
done
j=0
line=
while [ $j -lt $i ]; do
  line="$line ${y[$j]} ${order[$j]}"
  let j=$j+1
done
if [ 1 -eq $i ]; then
  line="$line $zero 1"
fi
exec new_irred_with_orders $memory $line
