#!/bin/sh
#
# $Id: new_irredf_and_indicate_with_orders,v 1.5 2006/12/27 19:09:52 jon Exp $
#
# Script to classify an irreducible representation
#
# Inputs
# $1: initial memory
# $2: temporary directory
# $3: a name for the form
# $4: generator a
# $5: order a
# $6: generator b
# $7: order b
# $8-: other generators and orders
#
# outputs will be of the form irred/${nor}_${i}_{1,..}
# where nor = znor $a and i is an available unused index
#
#
# Return codes
# 1: error in parameters
# 0: new irreducible
# 254: no nullity one element found
# 255: existing irreducible
#
usage="$0: usage: $0 <memory> <tmp directory> <form> <a> <order a> <b> <order b> [<other generators and orders>]"
if [ $# -lt 7 ]; then
  echo "$usage"
  exit 1;
fi
. functions
memory=$1
tmp_dir=$2
form=$3
a=$4
o_a=$5
b=$6
o_b=$7
if [ -e $a -a -e $b ]; then
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo $a and $b are not compatible
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
out=`new_irredf_with_orders $*`
ret=$?
echo $out
script=`echo $out | sed -e "s/^.*using script //g"`
new_name=`echo $out | sed -e "s/^Found a new irreducible //g;s/ of dimension .*$//g"`
if [ 0 -eq $ret ]; then
  shift 3
  i=1
  line=
  while [ 0 -lt $# ]; do
    if [ 1 -eq $# ]; then
      echo $usage
      exit 1
    fi
    line="$line ${new_name}_$i $2"
    shift 2
    let i=$i+1
  done
  indicatef_with_script $script $memory $tmp_dir $form ${new_name}_1 $o_a ${new_name}_2 $o_b
fi
exit 0
