#!/bin/sh
#
# $Id: new_irred_and_indicate_with_orders,v 1.6 2002/09/11 21:20:47 jon Exp $
#
# Script to classify an irreducible representation
#
# Inputs
# $1: initial memory
# $2: generator a
# $3: order a
# $4: generator b
# $5: order b
# $6-: other generators and orders
#
# outputs will be of the form irred/${nor}_${i}_{1,..}
# where nor = znor $a and i is an available unused index
#
#
# Return codes
# 1: error in parameters
# 0: new irreducible
# 254: no nullity one element found
# 255: existing irreducible
#
usage="$0: usage: $0 <memory> <a> <order a> <b> <order b> [<other generators and orders>]"
if [ $# -lt 5 ]; then
  echo "$usage"
  exit 1;
fi
. functions
memory=$1
a=$2
o_a=$3
b=$4
o_b=$5
if [ -e $a -a -e $b ]; then
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo $a and $b are not compatible
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
out=`new_irred_with_orders $*`
ret=$?
echo $out
script=`echo $out | sed -e "s/^.*using script //g"`
new_name=`echo $out | sed -e "s/^Found a new irreducible //g;s/ of dimension .*$//g"`
if [ 0 -eq $ret ]; then
  if [ 2 -eq `zchar $a` -o 2 -eq `zchar $b` ]; then
    indicate_with_script ${new_name}_1 ${new_name}_2 $script $o_a $o_b $memory
  fi
fi
exit 0
