#!/bin/sh
#
# $Id: new_irredf_and_indicate_with_orders,v 1.1 2002/08/02 09:04:09 jon Exp $
#
# Script to classify an irreducible representation
#
# Inputs
# $1: initial memory
# $2: temporary directory
# $3: generator a
# $4: order a
# $5: generator b
# $6: order b
# $7-: other generators and orders
#
# outputs will be of the form irred/${nor}_${i}_{1,..}
# where nor = znor $a and i is an available unused index
#
#
# Return codes
# 1: error in parameters
# 0: new irreducible
# 254: no nullity one element found
# 255: existing irreducible
#
usage="$0: usage: $0 <memory> <tmp directory> <a> <order a> <b> <order b> [<other generators and orders>]"
if [ $# -lt 6 ]; then
  echo $usage
  exit 1;
fi
. functions
memory=$1
tmp_dir=$2
a=$3
o_a=$4
b=$5
o_b=$6
if [ -e $a -a -e $b ]; then
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
    echo $a and $b are not compatible
    exit 1
  fi
else
  echo "$0: missing files $a or $b"
  exit 1
fi
out=`new_irredf_with_orders $*`
ret=$?
echo $out
script=`echo $out | sed -e "s/^.*using script //g"`
new_name=`echo $out | sed -e "s/^Found a new irreducible //g;s/ of dimension .*$//g"`
if [ 0 -eq $ret ]; then
  if [ 2 -eq `zchar $a` -o 2 -eq `zchar $b` ]; then
    indicatef_with_script ${new_name}_1 ${new_name}_2 $script $o_a $o_b $tmp_dir $memory
  fi
fi
exit 0
