#!/bin/bash
#
# $Id: pwr,v 1.2 2023/07/03 08:30:07 jon Exp $
#
# Emulate Aachen meataxe pwr
#
usage="$0: usage: $0 <power> <in> <out>"
if [ $# -ne 3 -a $# -ne 4 ]; then
  echo "$usage"
  exit 1;
fi
power $2 $1 $3
