#!/bin/sh
#
# $Id: qp,v 1.2 2002/09/11 21:20:47 jon Exp $
#
# Script to compute a the matrices Q and P required by tensor condense
#
# Inputs
# $1: a file containing the element E
# $2: memory to be used
# $3: the output Q
# $4: the output P
#
# Return codes
# 1: error in parameters
# 0: success
#
usage="$0: usage: $0 <E> <memory> <Q> <P>"
if [ $# -ne 4 ]; then
  echo "$usage"
  exit 1;
fi
name=$0
e=$1
memory=$2
q=$3
p=$4
r=`zbase $e . $q $memory`
ret=$?
if [ 0 -ne $ret ]; then
  echo "$name: zbase failed, terminating"
  exit 1
fi
if [ 0 -eq $r ]; then
  echo "$name: no fixed vectors, terminating"
  exit 1
fi
zss $q $e $p
ret=$?
if [ 0 -ne $ret ]; then
  echo "$name: zss failed, terminating"
  exit 1
fi
