#!/bin/sh
#
# $Id: singular_vector,v 1.1 2002/10/04 17:15:06 jon Exp $
#
# Script to find a singular vector form a form
#
# Inputs
# $1: initial memory
# $2: form S
# $3: output
#
# Return codes
# 1: error in parameters
# 0: success
# 255: no vector found
#
#set -v
. functions
usage="$0: usage: $0 <memory> <S> <o>"
if [ $# -ne 3 ]; then
  echo "$usage"
  exit 1;
fi
memory=$1
form=$2
o=$3
if [ -e $form ]; then
  nor=`znor $form`
  noc=`znoc $form`
  prime=`zprime $form`
  if [ 1 -eq $prime ]; then
    echo "$form cannot be a map, terminating"
    exit 1
  fi
  if [ $noc -ne $nor ]; then
    echo "form must be square, terminating"
    exit 1
  fi
  if [ 4 -lt $nor ]; then
    nor=4
  fi
else
  echo "$form not found, terminating"
  exit 1
fi
tmp=tmp${PPID}
zid $prime $nor $noc ${tmp}.0
ret=$?
if [ $ret -ne 0 ]; then
  rm -f ${tmp}*
  exit 1
fi
zspan ${tmp}.0 ${tmp}.1 $nor
ret=$?
if [ $ret -ne 0 ]; then
  rm -f ${tmp}*
  exit 1
fi
i=`znor ${tmp}.1`
j=0
while [ $j -lt $i ]; do
  zsel ${tmp}.1 ${tmp}.2 $j
  ret=$?
  if [ $ret -ne 0 ]; then
    rm -f ${tmp}*
    exit 1
  fi
  n=`norm $memory ${tmp}.2 $form`
  if [ "0" == "$n" ]; then
    cp -p ${tmp}.2 $o
    rm -f ${tmp}*
    exit 0
  fi
  let j=$j+1
done
rm -f ${tmp}*
exit 255
