#!/bin/sh
#
# $Id: singular_vector,v 1.2 2002/10/07 15:59:21 jon Exp $
#
# Script to find a singular vector for a form
#
# Inputs
# $1: initial memory
# $2: form S
# $3: output
#
# Return codes
# 1: error in parameters
# 0: success
# 255: no vector found
#
#set -v
. functions
usage="$0: usage: $0 <memory> <S> <o>"
if [ $# -ne 3 ]; then
  echo "$usage"
  exit 1;
fi
memory=$1
form=$2
o=$3
if [ -e $form ]; then
  nor=`znor $form`
  noc=`znoc $form`
  prime=`zprime $form`
  if [ 1 -eq $prime ]; then
    echo "$form cannot be a map, terminating"
    exit 1
  fi
  if [ $noc -ne $nor ]; then
    echo "form must be square, terminating"
    exit 1
  fi
  if [ 4 -lt $nor ]; then
    nor=4
  fi
else
  echo "$form not found, terminating"
  exit 1
fi
tmp=tmp${PPID}
zid $prime $nor $noc ${tmp}.0
ret=$?
if [ $ret -ne 0 ]; then
  rm -f ${tmp}*
  exit 1
fi
singular_vector_in_space $memory $form ${tmp}.0 $o
ret=$?
rm -f ${tmp}*
exit $ret
