#!/bin/sh
#
# $Id: split_with_subspace,v 1.8 2016/12/15 20:13:31 jon Exp $
#
# Script to split a representation given a particular subspace to work from
#
# Inputs
# $1: subspace with which to split
# $2: output subspace representation filename
# $3: output quotient representation filename
# $4: initial memory
# $5: generator a
#
# outputs will be of the form <$3>_<q>_<nor>
# where nor is number of rows, and q is the prime power
#
#
# Return codes
# 1: error in parameters
# 0: success
# 254: did not split
#
. functions
usage="$0: usage: $0 <s> <o_s> <o_q> <memory> <a>"
if [ $# -ne 5 ]; then
  echo "$usage"
  exit 1;
fi
s=$1
o_s=$2
o_q=$3
memory=$4
a=$5
if [ -e $a -a -e $s ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
  if [ $noc -ne `znoc $s` -o \( $q -ne `zprime $s` -a 1 -ne $q \) ]; then
    echo "$0: $a and $s are not compatible"
    exit 1
  fi
else
  echo "$0: missing files $a or $s"
  exit 1
fi
tmp=tmp${PPID}
mem_ok=0
dim=`znor $s`
let codim=$nor-$dim
if [ $dim -lt $nor ]; then
  zmu -m $memory $s $a ${tmp}.0 1>/dev/null
  zss -m $memory $s ${tmp}.0 ${o_s}
  zqs -m $memory $s $a ${o_q}
  rm -f ${tmp}.0
exit 0
else
  echo failed to split
  exit 254
fi
