#!/bin/sh
#
# $Id: split,v 1.9 2002/07/02 16:16:16 jon Exp $
#
# Script to split a representation
#
# Inputs
# $1: output filename base
# $2: generator a
# $3-: other generators
#
# outputs will be of the form <$3>_<q>_<nor>_$x
# where nor is number of rows, and q is the prime power
#
#
# Return codes
# 1: error in parameters
# 0: success
# 252: ran out of possible splitters
# 254: failed to split
# 255: irreducible
#
#set -v
. functions
usage="$0: usage: $0 <output_stem> <a> [<other generators>]"
if [ $# -lt 3 ]; then
  echo $usage
  exit 1;
fi
a=$2
o=$1
shift 2
if [ -e $a ]; then
  q=`zprime $a`
  nor=`znor $a`
  noc=`znoc $a`
  if [ $nor -ne $noc ]; then
    echo "$0: $a is not square"
    exit 1
  fi
else
  echo "$0: missing file $a"
  exit 1
fi
if [ 1 -eq $nor ]; then
# No point in further work on irreducibles
  exit 255
fi
id=id_${q}_$nor
if [ ! -e $id ]; then
  zid $q $nor $nor $id
fi
#
# Now look for something with nullity
#
tmp=tmp${PPID}
#
# Try 1 + a + b etc
#
b=$1
for i in 1 2 3 4 5 6 7 8 9 10; do
  echo using f$i to split
  f$i $id $a $b ${tmp}.1 ${tmp}.1
  if [ $? -ne 0 ]; then
    rm -f ${tmp}*
    exit 1
  fi
  split_with_element ${tmp}.1 $o 0 ${tmp}.2 $a $*
  ret=$?
# Only loop on nullity 0 or didn't split
  if [ $ret -ne 253 -a $ret -ne 254 ]; then
    rm -f ${tmp}*
    exit $ret
  fi
done
 If any generators are singular, try them
for x in $a $*; do
  split_with_element $x $o 0 ${tmp}.2 $a $*
  ret=$?
# Only loop on nullity 0 or didn't split
  if [ $ret -ne 253 -a $ret -ne 254 ]; then
    rm -f ${tmp}*
    exit $ret
  fi
done
echo searching for suitable element using zsums
# First compute o_a and o_b
#o_a=`singular_order $a`
#ret=$?
#if [ 0 -ne $ret ]; then
#  echo Cannot compute order of $a
#  rm -f ${tmp}*
#  exit 1
#fi
#o_b=`singular_order $b`
#ret=$?
#if [ 0 -ne $ret ]; then
#  echo Cannot compute order of $b
#  rm -f ${tmp}*
#  exit 254
#fi
i=0
for x in $a $*; do
  order=`singular_order $x`
  ret=$?
  if [ 1 -eq $ret ]; then
    echo Cannot compute order of $x
    rm -f ${tmp}*
    exit 1
  fi
  if [ 0 -eq $ret ]; then
    order[$i]=$order
    y[$i]=$x
    let i=$i+1
    if [ 2 -le $i ]; then
      break
    fi
  elif [ 255 -eq $ret ]; then
    continue
  else
    echo singular_order returns unexpected code $ret
    rm -f ${tmp}*
    exit 1
  fi
done
if [ 2 -ne $i ]; then
  rm -f ${tmp}*
  exit 254
fi
ok=0
memory=200
while [ $ok -eq 0 ]; do
  out=`zsums ${y[0]} ${y[1]} ${tmp}.zsums ${order[0]} ${order[1]} 5 5 $memory 2>/dev/null`
  ret=$?
  if [ 2 -eq $ret ]; then
    let memory=`more_memory $memory`
  elif [ 0 -eq $ret ]; then
    ok=1
    name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
    split_with_element ${name} $o 0 ${tmp}.2 $a $*
    ret=$?
    if [ $ret -eq 255 -o $ret -eq 0 ]; then
      rm -f ${tmp}*
      exit $ret
    fi
  else
    echo "Failed to find an element of nullity <= 5"
    rm -f ${tmp}*
    exit 254
  fi
done
rm -f ${tmp}*
exit 252
