#!/bin/sh
#
# $Id: split_all_decomp,v 1.2 2006/07/23 16:02:13 jon Exp $
#
# Script to split a decomposable representation completely
# Generally used over p' condensation subgroups
#
# Inputs
# $1: output filename base
# $1: generator a
# $2-: other generators
#
# Return codes
# 1: error in parameters
# 0: success
# 252: ran out of possible splitters
#
usage="$0: usage: $0 <output_stem> <generators>*"
if [ $# -lt 3 ]; then
  echo "$usage"
  exit 1;
fi
# Just a front end for split_all_sub. Don't ignore pathology
stem=$1
a=$2
shift 2
exec split_all_sub $stem 0 0 /dev/null $a $*
