#!/bin/sh
#
# $Id: sym_basis_delta,v 1.6 2004/06/21 20:38:33 jon Exp $
#
# Script to compute a symmetry basis wrt an ordered set of irreducibles,
# using delta words
#
# Inputs
# $1: a file containing the irreducible element names
# $2: memory to be used
# $3: the file to contain the symmetry basis
# $4: the file of multiplicities
# $5: whether to use the dual (0 => not, 1 => dual)
# $6: the file of delta word scripts
# $7-: generators for the condensation group
#
# Return codes
# 1: error in parameters
# 0: success
# 255: an irreducible was found outside the list
#
usage="$0: usage: $0 <irreducibles> <memory> <output basis> <output multiplicities> <dualise> <script> <generator 1> [<other generators>]"
if [ $# -lt 8 ]; then
  echo "$usage"
  exit 1;
fi
have_basis=0
name=$0
irreds=$1
memory=$2
out=$3
mult=$4
dualise=$5
deltas=`cat $6`
shift 6
gen_count=$#
tmp=tmp${PPID}
basis=${tmp}.31
local_basis=${tmp}.32
cat /dev/null > $mult
irred_num=1
for x in `cat $irreds`; do
  w=$x
#
# Cope with dual here
#
  if [ 1 -eq $dualise ]; then
    i=1
    names=
    while [ 0 -lt $i ]; do
      if [ -e ${x}_${i} ]; then
        names="$names ${x}_${i}"
      else
        break
      fi
      let i=$i+1
    done
    i=1
    dual_names=
    for y in $names; do
      dual $y ${tmp}_${i} $memory
      dual_names="$dual_names ${tmp}_${i}"
      let i=$i+1
    done
    r=`new_irred $memory $dual_names`
    ret=$?
    if [ 0 -eq $ret ]; then
      rm -f ${tmp}.*
      echo "$name: new unknown dual irreducible found for ${x}, terminating"
      exit 255
    elif [ 1 -eq $ret ]; then
      rm -f ${tmp}.*
      echo "$name: $r"
      exit 1
    elif [ 255 -ne $ret ]; then
      rm -f ${tmp}.*
      echo "$name: unexpected return $ret from new_irred, terminating"
      exit 1
    fi
    irr=`echo $r | sed -e "s/Existing irreducible //g;s/ found//g"`
    w=$irr
# Now find $w in list of irreds
    i=1
    for x in `cat $irreds`; do
      if [ ${w} = ${x} ]; then
        irred_num=$i
        echo Found ${w} at number $irred_num
        break
      fi
      let i=$i+1
    done
  fi
  i=1
  for x in $deltas; do
    if [ $i -eq $irred_num ]; then
      script=$x
      break
    fi
    let i=$i+1
  done
  wdim=`znor ${w}_1`
  y=`ls ${w}_1_I*`
  ret=$?
  if [ 0 -ne $ret ]; then
    echo "$name: failed to find irreducible script for ${w}, terminating"
    exit 1
  fi
  script_x=`echo $y | sed -e "s?${w}_1_??g"`
  ret=$?
  if [ 0 -ne $ret ]; then
    echo "$name: failed to produce irreducible script for ${w}, terminating"
    rm -f ${tmp}.*
    exit 1
  fi
  count=0
# Compute the delta word in the generators for irreducible X
  zscript -m $memory ${tmp}.0 ${tmp}.zscript $script $*
  ret=$?
  if [ 0 -ne $ret ]; then
    echo "$name: delta word computation failed for ${w}, terminating"
    exit 1
  fi
  dim=`znsf -m $memory ${tmp}.0 ${tmp}.1 .`
  ret=$?
  if [ 0 -ne $ret ]; then
    echo $dim
    echo "$name: nullspace computation failed for delta word for ${w}, terminating"
    exit 1
  fi
  if [ $dim -gt 0 ]; then
# First compute total space spun from image of gamma operator
    r=`zmspf -m $memory ${tmp}.1 ${tmp}.2 . $*`
    ret=$?
    if [ 0 -ne $ret ]; then
      rm -f ${tmp}.*
      echo $r
      echo "$name: failed to spin image of gamma, terminating"
      exit 1
    fi
    let tot=$r/$wdim
    echo tot=$tot, r=$r, wdim=$wdim, dim=$dim
    dim=`zsymb -m $memory $tot $wdim ${tmp}.1 ${tmp}.2 . $*`
    ret=$?
    if [ 0 -ne $ret ]; then
      rm -f ${tmp}.*
      echo $dim
      echo code $ret
      echo "$name: failed to base component for $w, terminating"
      exit 1
    fi
    if [ $r -ne $dim ]; then
      rm -f ${tmp}.*
      echo "$name: expected dimension $r for component $w but got $dim, terminating"
      exit 1
    fi
    count=$tot
    if [ 0 -eq $have_basis ]; then
      cp ${tmp}.2 $basis
      ret=$?
      have_basis=1
    else
      zjoin $basis ${tmp}.2 ${tmp}.3
      ret=$?
      if [ 0 -ne $ret ]; then
        rm -f ${tmp}.*
        echo "$name: unexpected failure in zjoin, terminating"
        exit 1
      fi
      cp ${tmp}.3 $basis
      ret=$?
    fi
    if [ 0 -ne $ret ]; then
      rm -f ${tmp}.*
      echo "$name: unexpected failure in cp, terminating"
      exit 1
    fi
  fi
  echo $count >> $mult
  let irred_num=$irred_num+1
done
if [ 0 -eq $have_basis ]; then
  rm -f ${tmp}.*
  echo "$name: no basis found, terminating"
  exit 1
fi
if [ `znor $basis` -ne `znor $1` ]; then
  rm -f ${tmp}.*
  echo "$name: not enough basis found"
  exit 255
fi
cp $basis $out
rm -f ${tmp}.*
exit 0
