#!/bin/sh
#
# $Id: three,v 1.1 2004/04/11 22:10:38 jon Exp $
#
# Script to produce _3 from _1
#
usage="$0: usage: $0 <a>"
if [ $# -ne 1 ]; then
  echo "$usage"
  exit 1
fi
echo $1 | sed -e "s/_1$/_3/g"
