#!/bin/sh
# Script to convert from meataxe 64 to meataxe 2000
# Expect to use back to back zpr znd zcv
# Ie roughly 2000/zpr $1 | zcv $2
# But zcv 2000 expects an input file rather than input on stdio
# meataxe 64 is expected to be on path
# meataxe 2000 in ~/install
#
# Return codes
# 1: error in parameters
# 0: success
usage="$0: usage: $0 <in> <out>"
if [ $# -ne 2 ]; then
  echo "$usage"
  exit 1;
fi
if [ -e $1 ]; then
  tmp=tmp${PPID}
  zpr $1 > ${tmp}
  ~/install/zcv ${tmp} $2
  rm ${tmp}
else
  echo "$0: missing file $1"
  exit 1
fi
