#!/bin/sh
#
# $Id: tspin_vectors,v 1.4 2002/10/14 09:24:05 jon Exp $
#
# Compute subspaces, with a memory limit,
# using tensor product generators
#
# Inputs
# $1 file of vectors to try, one at a time
# $2 number of vectors to use from the file
# $3 file stem for generators 1 (assumed to be <file stem>_{1,2})
# $4 file stem for generators 2 (assumed to be <file stem>_{1,2})
# $5 memory
# $6 start point within the file from which to get vectors
#
. functions
usage="$0: usage: $0 <vectors> <count> <input_stem 1> <input_stem 2> <memory> <first vector>"
if [ $# -ne 6 ]; then
  echo "$usage"
  exit 1
fi
# First to be tried
x=$6
# Last to look at
let y=$x+$2
# Two generators
a1=${3}_1
b1=${3}_2
a2=${4}_1
b2=${4}_2
# Temporary file stem
tmp=tmp${PPID}
memory=$5
while [ $x -lt $y ]; do
  echo Trying $x
  zsel $1 ${tmp}.0 $x
  ret=$?
  if [ 0 -ne $ret ]; then
    echo Failed to select vector $x, ignoring
    let x=$x+1
    continue
  fi
# Check that we haven't selected a zero vector
  rn=`zrn -m $memory ${tmp}.0`
  ret=$?
  if [ 0 -ne $ret ]; then
    echo rn returns $ret on for vector $x, ignoring
  else
    if [ $rn -eq 0 ]; then
      echo vector $x is zero and so not considered
    else
      sub=`ztsp -m $memory ${tmp}.0 $1.$x.ss $a1 $a2 $b1 $b2`
      ret=$?
      if [ $ret -eq 0 ]; then
        echo subspace $1.$x.ss of size $sub found for element $x
        rm -f ${tmp}.0
        exit
      elif [ $ret -eq 2 ]; then
        echo subspace ran out of memory for element $x
      else
        echo subspace failed for element $x with return $ret
      fi
    fi
    rm ${tmp}.0
  fi
  let x=$x+1
done
rm -f ${tmp}.0
echo Failed to find a subspace
exit 255
