#!/bin/sh
#
# $Id: two,v 1.3 2002/09/11 21:20:47 jon Exp $
#
# Script to produce _2 from _1
#
usage="$0: usage: $0 <a>"
if [ $# -ne 1 ]; then
  echo "$usage"
  exit 1
fi
echo $1 | sed -e "s/_1$/_2/g"
