#!/bin/bash
# Script to convert from meataxe 64 to meataxe 2000
# meataxe 64 is expected to be on path
# meataxe 2000 in ~/install
#
# Return codes
# 1: error in parameters
# 0: success
dir=`dirname $0`
usage="$0: usage: $0 <in> <out>"
if [ $# -ne 2 ]; then
  echo "$usage"
  exit 1;
fi
if [ -e $1 ]; then
   ${dir}/../bin/zexport64 $1 $2
else
  echo "$0: missing file $1"
  exit 1
fi
