#!/bin/bash
#
# Script to do zfln in meataxe 64 until a binary is available
#
# Parameters as for zfln in meataxe 2000
# ie [-v] [-m <memory>] <out_file_stem> <n> <nullity> <in_file a> <order a> <in_file b> <order b>
#
mem=
if [ "-m" = "$1" ]; then
    mem="-m $2"
    shift 2
fi
mg=
if [ "-mg" = "$1" ]; then
    mg="-mg $2"
    shift 2
fi
stem=$1
n=$2
nullity=$3
shift 3
# Now get elements and orders and construct
comline=
tmp=tmp$$
i=0
while [ $# -gt 0 ]; do
  # Get the element and convert
  name=${tmp}.$i
  to_m2000 $1 ${name}
  comline="${comline} ${name} $2"
  let i=$i+1
  shift 2
done
out=`~/install/zfln ${mem} ${mg} ${stem} ${n} ${nullity} ${comline}`
ret=$?
if [ 0 -eq $ret ]; then
  # Need to convert outfile back
  out_name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
  mv ${out_name} ${tmp}.out
  to_m64 ${tmp}.out ${out_name}
fi
rm -f ${tmp}.*
echo ${out}
exit ${ret}
