#!/bin/bash
#
# Script to do zmsb in meataxe 64
#
# Parameters as for zmsb in meataxe 2000
# ie [-m <memory] <infile> <outfile> <generators>
#
dir=`dirname $0`
if [ "-m" = "$1" ]; then
    shift 2
fi
if [ $# -le 3 ]; then
   echo "zmsb: bad parameters"
   echo "usage: zmsb [-m <memory] <infile> <outfile> <generators>"
   exit 1
fi
infile=$1
outfile=$2
shift 2
tmp=tmp${PPID}
out=`${dir}/../bin/zsb ${infile} ${tmp}.ss $* | egrep -v "^f" | egrep -v "siz"`
ret=$?
rm -f ${tmp}.ss.{bs,rem}
mv ${tmp}.ss.sb ${outfile}
echo $out
exit ${ret}
