#!/bin/bash
#
# Script to do zrn in meataxe 64
# Although we have a binary, it is command line incompatible
# with the meataxe 2000 scripts
#
# Parameters as for zrn in meataxe 2000
# ie [-m <memory] <infile>
#
dir=`dirname $0`
if [ "$1" = "-m" ]; then
    shift 2 # Ignore -m <memory
fi
if [ $# -ne 1 ]; then
   echo "zrn: bad parameters"
   echo "usage: zrn [-m <memory] <infile>"
   exit 1
fi
infile=$1
if [ ! -e ${infile} ]; then
    echo "zrn: No such file or directory" 1>&2
    echo "zrn: cannot open ${infile}, terminating" 1>&2
    exit 1
fi
tmp=tmp$$
out=`${dir}/../bin/zpe ${infile} ${tmp}.{bs,rem} | egrep -v "^f"`
ret=$?
if [ 0 -ne $ret ]; then
    exit 1
fi
echo ${out}
rm -f ${tmp}.{bs,rem}
exit $ret
